from fastapi import APIRouter
from pydantic import BaseModel, Field

router = APIRouter()

STOPWORDS = {
    "what", "is", "the", "a", "an",
    "how", "do", "i", "of", "for", "to", "in"}

NOTE = "Placeholder answer generated by keyword matching."

class AskRequest(BaseModel):
    question: str = Field(min_length=3)

class Match(BaseModel):
    id: int
    name: str
    score: int
    matched_keywords: list[str]

class AskResponse(BaseModel):
    question: str
    answer: str
    matches: list[Match]
    note: str

def extract_keywords(question):
    question = question.lower()

    cleaned = ""

    for ch in question:
        if ch.isalnum() or ch.isspace():
            cleaned += ch

    words = cleaned.split()
    keywords = set()

    for word in words:
        if word not in STOPWORDS:
            keywords.add(word)
    return keywords


def score_document(doc, keywords):
    tags = []

    for tag in doc["tags"]:
        tags.append(tag.lower())

    name_words = doc["name"].lower().split()
    category = doc["category"].lower()

    score = 0
    matched = []

    for keyword in keywords:

        if keyword in tags:
            score += 3
            matched.append(keyword)

        elif keyword in name_words:
            score += 2
            matched.append(keyword)

        elif keyword == category:
            score += 1
            matched.append(keyword)
    return score, matched


def sort_matches(match):
    return match.score


@router.post("/ask", response_model=AskResponse)
def ask(request: AskRequest):

    keywords = extract_keywords(request.question)

    scored = []

    for doc in get_all_documents():

        score, matched = score_document(doc, keywords)

        if score > 0:
            result = Match(
                id=doc["id"],
                name=doc["name"],
                score=score,
                matched_keywords=matched
            )

            scored.append(result)

    scored.sort(key=sort_matches, reverse=True)

    top = scored[:3]

    if len(top) > 0:
        answer = (
            "Based on keyword matching, the most relevant document is '"
            + top[0].name
            + "'."
        )
    else:
        answer = "No matching documents found for your question."

    return AskResponse(
        question=request.question,
        answer=answer,
        matches=top,
        note=NOTE
    )